class Stocks:
    def __init__(self,sector):
        self.sector = sector
        self.quotes = self.setQuotes()

    def setQuotes(self):
        if self.sector == 'nifty50':
            return ['ADANIENT','COALINDIA','ADANIPORTS','UPL','TATAMOTORS','NESTLEIND','BPCL','GRASIM','DRREDDY','ONGC','ITC','TATASTEEL',
                    'WIPRO','CIPLA','POWERGRID','SBIN','TECHM','APOLLOHOSP','HCLTECH','KOTAKBANK','ICICIBANK','HDFCLIFE','INDUSINDBK','INFY',
                    'HEROMOTOCO','DIVISLAB','TCS','JSWSTEEL','AXISBANK','HINDALCO','SUNPHARMA','RELIANCE','TITAN','NTPC','ASIANPAINT','LT','SBILIFE',
                    'TATACONSUM','BAJFINANCE','MARUTI','HDFCBANK','BAJAJFINSV','LTIM','BRITANNIA','BAJAJ-AUTO','ULTRACEMCO','HINDUNILVR','BHARTIARTL','EICHERMOT']
        
        elif self.sector == 'nifty100':
            return ['TATACONSUM','MOTHERSON','TATAMOTORS','GAIL','ADANIGREEN','DABUR','TATAMTRDVR','IRCTC','TORNTPHARM',
              'MCDOWELL-N','ADANIENSOL','CHOLAFIN','BAJAJ-AUTO','NESTLEIND','GODREJCP','JINDALSTEL','PGHH','SIEMENS','BERGEPAINT',
              'ADANIENT','TVSMOTOR','BRITANNIA','AMBUJACEM','HINDUNILVR','ICICIPRULI','EICHERMOT','INDIGO','TATASTEEL','TRENT','BAJFINANCE',
              'PIIND','SHREECEM','BOSCHLTD','ATGL','ABB','ADANIPORTS','ULTRACEMCO','TATAPOWER','SHRIRAMFIN','SRF','BEL','LTIM','ZOMATO','BAJAJFINSV',
              'DMART','ZYDUSLIFE','MARUTI','WIPRO','AWL','MARICO','PNB','LICI','HDFCBANK','VEDL','SBICARD','HAVELLS','PIDILITIND','LT','TCS','HINDALCO',
              'HAL','VBL','ASIANPAINT','COLPAL','SUNPHARMA','BAJAJHLDNG','SBILIFE','HDFCLIFE','UPL','HCLTECH','JSWSTEEL','GRASIM','NAUKRI','ITC','DLF',
              'BHARTIARTL','HEROMOTOCO','AXISBANK','RELIANCE','ICICIBANK','TITAN','DIVISLAB','ICICIGI','CIPLA','BANKBARODA','KOTAKBANK','INDUSINDBK','APOLLOHOSP',
              'DRREDDY','CANBK','TECHM','POWERGRID','NTPC','COALINDIA','INFY','ONGC','MUTHOOTFIN','SBIN','IOC','BPCL']
        
        elif self.sector == 'Ind':
            return ["INFY","TCS"]
        
    def getQuotes(self):
        return self.quotes
    